bases:
- ../../base

patches:
- target:
    kind: Deployment
    name: website
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 016194978976.dkr.ecr.us-east-1.amazonaws.com/multienv-vote-feature-new1:f0125d6b
